name: khushboo
favicon: null
layout_spectrum: 0.4382767444476485
typography_spectrum: 0.3992736879736185
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8271187427453697
  lightness: 0.03707868349738419
  saturation: 0.4937690137885511
  rhythmicContrast: 0.47138628945685923
purpose: []
